STOCK_SYMBOLS = [
    # Financial Services
    "HDFCBANK",
    "ICICIBANK",
    "SBIN",
    "AXISBANK",
    "KOTAKBANK",
    "INDUSINDBK",
    "BAJFINANCE",
    "BAJAJFINSV",
    "SHRIRAMFIN",
    "HDFCLIFE",
    "SBILIFE",
    "ICICIPRULI",
    "ICICIGI",
    "PNB",
    "BANKBARODA",

    # Information Technology
    "TCS",
    "INFY",
    "HCLTECH",
    "WIPRO",
    "TECHM",
    "LTM",
    "MPHASIS",
    "PERSISTENT",
    "COFORGE",
    "OFSS",

    # Energy
    "RELIANCE",
    "ONGC",
    "NTPC",
    "POWERGRID",
    "COALINDIA",
    "BPCL",
    "IOC",
    "GAIL",
    "ADANIENSOL",
    "ADANIGREEN",

    # Automobile
    "MARUTI",
    "M&M",
    "TMPV",
    "EICHERMOT",
    "HEROMOTOCO",
    "BAJAJ-AUTO",
    "TVSMOTOR",
    "MOTHERSON",
    "BOSCHLTD",
    "ASHOKLEY",

    # FMCG / Consumer
    "ITC",
    "HINDUNILVR",
    "NESTLEIND",
    "BRITANNIA",
    "TATACONSUM",
    "DABUR",
    "GODREJCP",
    "MARICO",
    "COLPAL",
    "TRENT",

    # Healthcare
    "SUNPHARMA",
    "DRREDDY",
    "CIPLA",
    "DIVISLAB",
    "APOLLOHOSP",
    "MAXHEALTH",
    "TORNTPHARM",
    "ZYDUSLIFE",
    "LUPIN",
    "AUROPHARMA",

    # Metals & Mining
    "TATASTEEL",
    "JSWSTEEL",
    "HINDALCO",
    "VEDL",
    "JINDALSTEL",
    "NMDC",
    "SAIL",
    "HINDZINC",

    # Infrastructure & Capital Goods
    "LT",
    "ADANIENT",
    "ADANIPORTS",
    "BEL",
    "HAL",
    "SIEMENS",
    "ABB",
    "BHEL",
    "CUMMINSIND",
    "RVNL",

    # Services
    "BHARTIARTL",
    "INDIGO",
    "ETERNAL",
    "DMART",
    "IRCTC",
    "INDHOTEL",
    "JIOFIN",

    # Materials / Consumer Durables
    "PIDILITIND",
    "SRF",
    "UPL",
    "ASIANPAINT",
    "ULTRACEMCO",
    "GRASIM",
    "SHREECEM",
    "AMBUJACEM",
    "TITAN",
    "HAVELLS",

    # More widely traded NSE equities
    "CANBK",
    "FEDERALBNK",
    "IDFCFIRSTB",
    "AUBANK",
    "BANDHANBNK",
    "UNIONBANK",
    "BANKINDIA",
    "INDIANB",
    "YESBANK",
    "RBLBANK",
    "CHOLAFIN",
    "MUTHOOTFIN",
    "MANAPPURAM",
    "PFC",
    "RECLTD",
    "IREDA",
    "HUDCO",
    "CONCOR",
    "DELHIVERY",
    "LTIM",
    "LTTS",
    "DIXON",
    "POLYCAB",
    "KEI",
    "CROMPTON",
    "VOLTAS",
    "BATAINDIA",
    "PAGEIND",
    "VBL",
    "NYKAA",
    "KAYNES",
    "ABBOTINDIA",
    "BIOCON",
    "GLENMARK",
    "LALPATHLAB",
    "FORTIS",
    "PATANJALI",
    "TATACHEM",
    "LINDEINDIA",
    "GODREJPROP",
    "OBEROIRLTY",
    "DLF",
    "PHOENIXLTD",
    "PRESTIGE",
    "INDUSTOWER",
    "ADANIPOWER",
    "JSWENERGY",
    "NHPC",
    "INOXWIND",
    "TATATECH",
]
